export const navLinks = [
  { name: 'Projects', path: '/projects' },
  { name: 'Games', path: '/games' },
  { name: 'Tech', path: '/blog' },
] as const;

export const authors = ['EKO', 'mingke'] as const;

export const tags = [
  'AI',
  'AWS',
  'Books',
  'Career',
  'Certification',
  'Django',
  'Docker',
  'FastAPI',
  'Git',
  'Github Actions',
  'Gunicorn',
  'JavaScript',
  'Kiro',
  'MCP',
  'NaverCloud',
  'Nextjs',
  'Nodejs',
  'PostgreSQL',
  'pre-commit',
  'Programming',
  'Prompt Engineering',
  'Pydantic',
  'Pytest',
  'Python',
  'Railway',
  'React',
  'Redis',
  'Rust',
  'SQLAlchemy',
  'Study',
  'Supabase',
  'Swagger',
  'Terraform',
  'Tools',
  'Vercel',
  'VSCode',
  'Writing',
  '오름캠프',
  '기타',
] as const;
